### PR TITLE
docs(readme) Added Made with TypeScript badge

### PR DESCRIPTION
**Pull request by Sapphire-code**
## Description

Fixes # 

### Type of change

- [ ] Bug fix (added a non-breaking change which fixes an issue)
- [ ] New feature (added a non-breaking change which adds functionality)
- [x] Updated documentation (updated the readme, templates, or other repo files)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [x] Tested endpoints locally

## Checklist:

- [x] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/custom-icon-badges/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [x] The code is properly formatted and is consistent with the existing code style
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Sapphire-code** [comment]
just added 2 new badges describing, "Made with love and typescript".
pretty small pull request to be honest

**Comment by DenverCoder1** [comment]
The badges don't look bad, but it's also a different style from the rest of the badges in the readme.

Maybe instead it could be made with shields.io to make it go with the Powered by Heroku better, for example,

<a href="https://www.typescriptlang.org/">Made with TypeScript</a>

```html
<a href="https://www.typescriptlang.org/"><img alt="Made with TypeScript" title="Made with TypeScript" src="https://img.shields.io/badge/-Made_with_Typescript-3178C6?style=for-the-badge&logo=typescript&logoColor=white"/></a>
```

Let me know what you think.

**Comment by Sapphire-code** [comment]
Oh yea, totally makes sense.
ill modify the pull request to add that I guess.

**Review by DenverCoder1 — APPROVED** [review]
Looks great! Thanks for the contribution :tada:

**Pull request merged**
